version: '3.4'

services:
  mypoc.api1:
    image: mypoc.mypocapi1:latest
    build: 
      context: ./MyPoc.Api1
      dockerfile: Dockerfile
    ports:
      - 8080:80

  mypoc.web:
    image: mypoc.mypocweb:latest
    build: 
      context: ./MyPoc.Web
      dockerfile: Dockerfile
    ports:
      - 8001:80  